RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Workshop"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false

uglyUrls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  description = "Workshop"
  author = "AWS"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = true
  disableLandingPageButton = true
  disableAssetsBusting = true
  disableLanguageSwitchingButton = true
  disableShortcutsTitle = false
  disableInlineCopyToClipBoard = true
  showVisitedLinks = true
  landingPageURL = "/index.html"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Session Feedback"
url = "mailto:email@amazon.com?subject=Contact"
weight = 10