schema:
  format:
    openapi: "3.0.0"
  pipeline_input_type: "PipelineInputs"
  service_input_type: "ServiceInputs"

  types:
    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        environment_account_ids:
          type: string
          pattern: '^$|^\d{12}(,\d{12})*$'
          description: "The environment account ids for service instances using cross account environment, separated by ,"
          default: ""
          maxLength: 200

    ServiceInputs:
      type: object
      description: "Service input properties"
      properties:
        environment_account_ids:
          type: string
          pattern: '^$|^\d{12}(,\d{12})*$'
          description: "The environment account ids for service instances using cross account environment, separated by ,"
          default: ""
          maxLength: 200