schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EnvironmentInput"
  types:
    EnvironmentInput:
      required:
        - application_name
        - cost_center
        - lob_owner
      type: object
      description: "Input properties for my environment"
      properties:
        application_name:
          type: string
          description: "ServiceCatalog AppRegistry application name."
        cost_center:
          type: string
          description: "cost_center"
        lob_owner:
          type: string
          description: "lob_owner"
