schema:
  format:
    openapi: "3.0.0"
  service_input_type: "LoadBalancedServiceInput"
  pipeline_input_type: "PipelineInputs"

  types:
    LoadBalancedServiceInput:
      type: object
      description: "Input properties for a loadbalanced Fargate service"
      properties:
        port:
          type: number
          description: "The port to route traffic to"
          default: 80
          minimum: 0
          maximum: 65535
        path:
          type: string
          description: "the uri path to route traffic to"
          default: "*"
        health_check_path:
          type: string
          description: "path to perform the health check on the service"
          default: "/health"
        uri_priority:
          type: number
          description: "uri path priority. must be unique in environment"
          default: 5
          minimum: 1
          maximum: 1000
        desired_count:
          type: number
          description: "The default number of Fargate tasks you want running"
          default: 1
          minimum: 1
        task_size:
          type: string
          description: "The size of the task you want to run"
          enum: ["x-small", "small", "medium", "large", "x-large"]
          default: "x-small"
        image:
          type: string
          description: "The name/url of the container image"
          default: "public.ecr.aws/z9d2n7e1/nginx:1.21.0"
          minLength: 1
          maxLength: 200
        DBName:
          type: string
          description: "Database name"
          default: "mydb"
          minLength: 1
          maxLength: 64
          pattern: '[a-zA-Z][a-zA-Z0-9]*'
        DBInstanceClass:
          type: string
          description: "Database instance class"
          default: "db.t3.medium"
        DBUsername:
          type: string
          description: "Username for MySQL database access"
          default: "admin"
          minLength: 1
          maxLength: 16
          pattern: '[a-zA-Z][a-zA-Z0-9]*'
        DBPassword:
          type: string
          pattern: '[a-zA-Z0-9]*'
          description: "Password MySQL database access"
          default: "myAwesomePassword"
          minLength: 8
          maxLength: 41

    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        dockerfile:
          type: string
          description: "The location of the Dockerfile to build"
          default: "Dockerfile"
          minLength: 1
          maxLength: 100
        unit_test_command:
          type: string
          description: "The command to run to unit test the application code"
          default: "echo 'add your unit test command here'"
          minLength: 1
          maxLength: 200
        environment_account_ids:
          type: string
          pattern: '^$|^\d{12}(,\d{12})*$'
          description: "The environment account ids for service instances using cross account environment, separated by ,"
          default: ""
          maxLength: 200

