AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an S3 Bucket and Cloudfront Distribution to host static sites
Mappings:
  # The VPC and subnet configuration is passed in via the environment spec.
  EnvironmentNameConfig:
    Environment:
      Name: '{{ environment.name}}'
Resources:
  CloudfrontDistroOrigin:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Identity for S3CloudFrontCloudfrontDistroOrigin
  CloudfrontDistro:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          TargetOriginId: S3CloudFrontCloudfrontDistroOrigin
          ViewerProtocolPolicy: allow-all
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName: {{ environment.outputs.S3RegionalDomainName}}
            Id: S3CloudFrontCloudfrontDistroOrigin
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - origin-access-identity/cloudfront/
                    - Ref: CloudfrontDistroOrigin
      Tags:
        - Key: ProtonEnvironment
          Value: !FindInMap ['EnvironmentNameConfig', 'Environment', 'Name']
                    
# These output values will be available to service templates to use.
Outputs:
  CloudFrontDomainName:
    Description: Domain name of the Cloudfront distribution
    Value: !GetAtt CloudfrontDistro.DomainName
  CloudFrontID:
    Description: ID of the Cloudfront distribution
    Value: !Ref CloudfrontDistro



